// <auto-generated />
namespace Summary.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class integrate_permission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(integrate_permission));
        
        string IMigrationMetadata.Id
        {
            get { return "202211210744358_integrate_permission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
